name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Build App
        run: |
          cargo install dioxus-cli
          dx build --release

      - name: Publish App & Documentation
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf . || true
          mv target/dx/personal_page/release/web/public/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages